# -*- coding: utf-8 -*-
"""GoodQuestion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ViKuOQtg0bRn_h_jOwpb6knzyJY-t5OU
"""

import pandas as pd
import os
import csv
import json 
import sys

"""# Import the data"""

DATA_DIR = "raw_data"
for csv in os.listdir(DATA_DIR):
  df = pd.read_csv(DATA_DIR+"/"+csv)
  df.drop(' BSSID', axis=1, inplace=True)
  df.drop(' Probed ESSIDs', axis=1, inplace=True)
  df.drop(' First time seen', axis=1, inplace=True)
  df.columns = [
    'mac',
    'last_seen',
    'power',
    'num_packets'
  ]

#print(df)
data_dictionary = df.to_dict() 
#print(data_dictionary)
  #from_dictionary = pd.DataFrame.from_dict(data_dictionary, orient='index', columns=['A', 'B', 'C', 'D'])